// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRoster(ctx context.Context, arg CreateRosterParams) (Roster, error)
	DeletePlayerFromRoster(ctx context.Context, arg DeletePlayerFromRosterParams) error
	DeleteRosterEntry(ctx context.Context, id uuid.UUID) error
	DeleteTeamRoster(ctx context.Context, fantasyTeamID uuid.UUID) error
	GetBenchRosterPlayers(ctx context.Context, fantasyTeamID uuid.UUID) ([]Roster, error)
	GetPlayerOnRoster(ctx context.Context, arg GetPlayerOnRosterParams) (Roster, error)
	GetRoster(ctx context.Context, id uuid.UUID) (Roster, error)
	GetRosterPlayersByAcquisitionType(ctx context.Context, arg GetRosterPlayersByAcquisitionTypeParams) ([]Roster, error)
	GetRosterPlayersByFantasyTeam(ctx context.Context, fantasyTeamID uuid.UUID) ([]Roster, error)
	GetRosterPlayersByFantasyTeamAndPosition(ctx context.Context, arg GetRosterPlayersByFantasyTeamAndPositionParams) ([]Roster, error)
	GetStartingRosterPlayers(ctx context.Context, fantasyTeamID uuid.UUID) ([]Roster, error)
	UpdateRosterPlayerKeeperData(ctx context.Context, arg UpdateRosterPlayerKeeperDataParams) (Roster, error)
	UpdateRosterPlayerPosition(ctx context.Context, arg UpdateRosterPlayerPositionParams) (Roster, error)
	UpdateRosterPositionAndKeeperData(ctx context.Context, arg UpdateRosterPositionAndKeeperDataParams) (Roster, error)
}

var _ Querier = (*Queries)(nil)
