// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error)
	CreateDraftPick(ctx context.Context, arg CreateDraftPickParams) (DraftPick, error)
	CreateDraftPickBatch(ctx context.Context, arg CreateDraftPickBatchParams) error
	DeleteDraft(ctx context.Context, id uuid.UUID) error
	DeleteDraftPicksByDraft(ctx context.Context, draftID uuid.UUID) error
	FetchOutboxByID(ctx context.Context, id uuid.UUID) (FetchOutboxByIDRow, error)
	FetchUnsentOutbox(ctx context.Context, limit int32) ([]FetchUnsentOutboxRow, error)
	GetDraft(ctx context.Context, id uuid.UUID) (Draft, error)
	GetDraftPick(ctx context.Context, id uuid.UUID) (DraftPick, error)
	GetDraftPicksByDraft(ctx context.Context, draftID uuid.UUID) ([]DraftPick, error)
	GetDraftPicksByRound(ctx context.Context, arg GetDraftPicksByRoundParams) ([]DraftPick, error)
	GetNextPickForDraft(ctx context.Context, draftID uuid.UUID) (DraftPick, error)
	InsertOutboxPickMade(ctx context.Context, arg InsertOutboxPickMadeParams) error
	MakePick(ctx context.Context, arg MakePickParams) (int64, error)
	MarkOutboxSent(ctx context.Context, id uuid.UUID) error
	UpdateDraftPickPlayer(ctx context.Context, arg UpdateDraftPickPlayerParams) (DraftPick, error)
	UpdateDraftStatus(ctx context.Context, arg UpdateDraftStatusParams) (Draft, error)
}

var _ Querier = (*Queries)(nil)
