sports:
  enabled_plugins:
    - nfl
  
  plugins:
    nfl:
      api_base_url: "https://api.sportsdata.io"
      page_size: 100
      timeout: 30s
      
database:
  host: "localhost"
  port: 5432
  name: "dynasty"
  
logging:
  level: "info"
  format: "json"