services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dynasty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats-1:
    image: nats:2.10.0
    container_name: nats-1
    ports:
      - "4222:4222"   # Client port (mapped only for node 1)
      - "8222:8222"   # HTTP monitoring
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats1_data:/data/jetstream
    command: ["-c", "/etc/nats/nats-server.conf"]
    environment:
      - NATS_SERVER_NAME=nats-1
    depends_on:
      - postgres

  nats-2:
    image: nats:2.10.0
    container_name: nats-2
    ports:
      - "4223:4222"   # expose client port on host:container 4223→4222
      - "8223:8222"   # HTTP monitoring
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats2_data:/data/jetstream
    command: ["-c", "/etc/nats/nats-server.conf"]
    environment:
      - NATS_SERVER_NAME=nats-2

  nats-3:
    image: nats:2.10.0
    container_name: nats-3
    ports:
      - "4224:4222"   # expose client port on host:container 4224→4222
      - "8224:8222"   # HTTP monitoring
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats3_data:/data/jetstream
    command: ["-c", "/etc/nats/nats-server.conf"]
    environment:
      - NATS_SERVER_NAME=nats-3

volumes:
  postgres_data:
  nats1_data:
  nats2_data:
  nats3_data:
