// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error)
	DeleteLeague(ctx context.Context, id uuid.UUID) error
	GetLeague(ctx context.Context, id uuid.UUID) (League, error)
	GetLeaguesByCommissioner(ctx context.Context, commissionerID uuid.UUID) ([]League, error)
	UpdateLeague(ctx context.Context, arg UpdateLeagueParams) (League, error)
	UpdateLeagueSettings(ctx context.Context, arg UpdateLeagueSettingsParams) (League, error)
	UpdateLeagueStatus(ctx context.Context, arg UpdateLeagueStatusParams) (League, error)
}

var _ Querier = (*Queries)(nil)
