// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFantasyTeam(ctx context.Context, arg CreateFantasyTeamParams) (FantasyTeam, error)
	DeleteFantasyTeam(ctx context.Context, id uuid.UUID) error
	GetFantasyTeam(ctx context.Context, id uuid.UUID) (FantasyTeam, error)
	GetFantasyTeamByLeagueAndOwner(ctx context.Context, arg GetFantasyTeamByLeagueAndOwnerParams) (FantasyTeam, error)
	GetFantasyTeamsByLeague(ctx context.Context, leagueID uuid.UUID) ([]FantasyTeam, error)
	GetFantasyTeamsByOwner(ctx context.Context, ownerID uuid.UUID) ([]FantasyTeam, error)
	UpdateFantasyTeam(ctx context.Context, arg UpdateFantasyTeamParams) (FantasyTeam, error)
}

var _ Querier = (*Queries)(nil)
