// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	DeleteTeam(ctx context.Context, id uuid.UUID) error
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamByExternalID(ctx context.Context, arg GetTeamByExternalIDParams) (Team, error)
	GetTeamBySportIdAndAlias(ctx context.Context, arg GetTeamBySportIdAndAliasParams) (Team, error)
	ListAllTeams(ctx context.Context) ([]Team, error)
	ListTeamsBySport(ctx context.Context, sportID string) ([]Team, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
