// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FetchOutboxByID(ctx context.Context, id uuid.UUID) (FetchOutboxByIDRow, error)
	FetchUnsentOutbox(ctx context.Context, limit int32) ([]FetchUnsentOutboxRow, error)
	InsertOutboxDraftCompleted(ctx context.Context, arg InsertOutboxDraftCompletedParams) error
	InsertOutboxDraftPaused(ctx context.Context, arg InsertOutboxDraftPausedParams) error
	InsertOutboxDraftResumed(ctx context.Context, arg InsertOutboxDraftResumedParams) error
	InsertOutboxDraftStarted(ctx context.Context, arg InsertOutboxDraftStartedParams) error
	InsertOutboxPickMade(ctx context.Context, arg InsertOutboxPickMadeParams) error
	InsertOutboxPickStarted(ctx context.Context, arg InsertOutboxPickStartedParams) error
	MarkOutboxSent(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
