// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type NflPlayerProfile struct {
	PlayerID     uuid.UUID      `json:"player_id"`
	Position     sql.NullString `json:"position"`
	Status       sql.NullString `json:"status"`
	College      sql.NullString `json:"college"`
	JerseyNumber sql.NullInt16  `json:"jersey_number"`
	Experience   sql.NullInt16  `json:"experience"`
	BirthDate    sql.NullTime   `json:"birth_date"`
	HeightCm     sql.NullInt32  `json:"height_cm"`
	WeightKg     sql.NullInt32  `json:"weight_kg"`
	HeightDesc   sql.NullString `json:"height_desc"`
	WeightDesc   sql.NullString `json:"weight_desc"`
}

type Player struct {
	ID         uuid.UUID     `json:"id"`
	SportID    string        `json:"sport_id"`
	ExternalID string        `json:"external_id"`
	FullName   string        `json:"full_name"`
	TeamID     uuid.NullUUID `json:"team_id"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Sport struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	PluginKey string    `json:"plugin_key"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID              uuid.UUID      `json:"id"`
	SportID         string         `json:"sport_id"`
	ExternalID      string         `json:"external_id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	City            string         `json:"city"`
	Coach           sql.NullString `json:"coach"`
	Owner           sql.NullString `json:"owner"`
	Stadium         sql.NullString `json:"stadium"`
	EstablishedYear sql.NullInt32  `json:"established_year"`
	CreatedAt       time.Time      `json:"created_at"`
}
