// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: nfl_player_profile.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNFLPlayerProfile = `-- name: CreateNFLPlayerProfile :one
INSERT INTO nfl_player_profiles (
    player_id,
    height_cm,
    weight_kg,
    group_role,
    position,
    age,
    height_desc,
    weight_desc,
    college,
    jersey_number,
    salary_desc,
    experience
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
) RETURNING player_id, height_cm, weight_kg, group_role, position, age, height_desc, weight_desc, college, jersey_number, salary_desc, experience
`

type CreateNFLPlayerProfileParams struct {
	PlayerID     uuid.UUID      `json:"player_id"`
	HeightCm     sql.NullInt32  `json:"height_cm"`
	WeightKg     sql.NullInt32  `json:"weight_kg"`
	GroupRole    sql.NullString `json:"group_role"`
	Position     sql.NullString `json:"position"`
	Age          sql.NullInt32  `json:"age"`
	HeightDesc   sql.NullString `json:"height_desc"`
	WeightDesc   sql.NullString `json:"weight_desc"`
	College      sql.NullString `json:"college"`
	JerseyNumber sql.NullInt16  `json:"jersey_number"`
	SalaryDesc   sql.NullString `json:"salary_desc"`
	Experience   sql.NullInt16  `json:"experience"`
}

func (q *Queries) CreateNFLPlayerProfile(ctx context.Context, arg CreateNFLPlayerProfileParams) (NflPlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, createNFLPlayerProfile,
		arg.PlayerID,
		arg.HeightCm,
		arg.WeightKg,
		arg.GroupRole,
		arg.Position,
		arg.Age,
		arg.HeightDesc,
		arg.WeightDesc,
		arg.College,
		arg.JerseyNumber,
		arg.SalaryDesc,
		arg.Experience,
	)
	var i NflPlayerProfile
	err := row.Scan(
		&i.PlayerID,
		&i.HeightCm,
		&i.WeightKg,
		&i.GroupRole,
		&i.Position,
		&i.Age,
		&i.HeightDesc,
		&i.WeightDesc,
		&i.College,
		&i.JerseyNumber,
		&i.SalaryDesc,
		&i.Experience,
	)
	return i, err
}

const deleteNFLPlayerProfile = `-- name: DeleteNFLPlayerProfile :exec
DELETE FROM nfl_player_profiles WHERE player_id = $1
`

func (q *Queries) DeleteNFLPlayerProfile(ctx context.Context, playerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNFLPlayerProfile, playerID)
	return err
}

const getNFLPlayerProfile = `-- name: GetNFLPlayerProfile :one
SELECT player_id, height_cm, weight_kg, group_role, position, age, height_desc, weight_desc, college, jersey_number, salary_desc, experience FROM nfl_player_profiles WHERE player_id = $1
`

func (q *Queries) GetNFLPlayerProfile(ctx context.Context, playerID uuid.UUID) (NflPlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getNFLPlayerProfile, playerID)
	var i NflPlayerProfile
	err := row.Scan(
		&i.PlayerID,
		&i.HeightCm,
		&i.WeightKg,
		&i.GroupRole,
		&i.Position,
		&i.Age,
		&i.HeightDesc,
		&i.WeightDesc,
		&i.College,
		&i.JerseyNumber,
		&i.SalaryDesc,
		&i.Experience,
	)
	return i, err
}

const getNFLPlayerProfileByExternalID = `-- name: GetNFLPlayerProfileByExternalID :one
SELECT npp.player_id, npp.height_cm, npp.weight_kg, npp.group_role, npp.position, npp.age, npp.height_desc, npp.weight_desc, npp.college, npp.jersey_number, npp.salary_desc, npp.experience FROM nfl_player_profiles npp
JOIN players p ON npp.player_id = p.id
WHERE p.sport_id = $1 AND p.external_id = $2
`

type GetNFLPlayerProfileByExternalIDParams struct {
	SportID    string `json:"sport_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetNFLPlayerProfileByExternalID(ctx context.Context, arg GetNFLPlayerProfileByExternalIDParams) (NflPlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, getNFLPlayerProfileByExternalID, arg.SportID, arg.ExternalID)
	var i NflPlayerProfile
	err := row.Scan(
		&i.PlayerID,
		&i.HeightCm,
		&i.WeightKg,
		&i.GroupRole,
		&i.Position,
		&i.Age,
		&i.HeightDesc,
		&i.WeightDesc,
		&i.College,
		&i.JerseyNumber,
		&i.SalaryDesc,
		&i.Experience,
	)
	return i, err
}

const updateNFLPlayerProfile = `-- name: UpdateNFLPlayerProfile :one
UPDATE nfl_player_profiles SET
    height_cm = $2,
    weight_kg = $3,
    group_role = $4,
    position = $5,
    age = $6,
    height_desc = $7,
    weight_desc = $8,
    college = $9,
    jersey_number = $10,
    salary_desc = $11,
    experience = $12
WHERE player_id = $1
RETURNING player_id, height_cm, weight_kg, group_role, position, age, height_desc, weight_desc, college, jersey_number, salary_desc, experience
`

type UpdateNFLPlayerProfileParams struct {
	PlayerID     uuid.UUID      `json:"player_id"`
	HeightCm     sql.NullInt32  `json:"height_cm"`
	WeightKg     sql.NullInt32  `json:"weight_kg"`
	GroupRole    sql.NullString `json:"group_role"`
	Position     sql.NullString `json:"position"`
	Age          sql.NullInt32  `json:"age"`
	HeightDesc   sql.NullString `json:"height_desc"`
	WeightDesc   sql.NullString `json:"weight_desc"`
	College      sql.NullString `json:"college"`
	JerseyNumber sql.NullInt16  `json:"jersey_number"`
	SalaryDesc   sql.NullString `json:"salary_desc"`
	Experience   sql.NullInt16  `json:"experience"`
}

func (q *Queries) UpdateNFLPlayerProfile(ctx context.Context, arg UpdateNFLPlayerProfileParams) (NflPlayerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateNFLPlayerProfile,
		arg.PlayerID,
		arg.HeightCm,
		arg.WeightKg,
		arg.GroupRole,
		arg.Position,
		arg.Age,
		arg.HeightDesc,
		arg.WeightDesc,
		arg.College,
		arg.JerseyNumber,
		arg.SalaryDesc,
		arg.Experience,
	)
	var i NflPlayerProfile
	err := row.Scan(
		&i.PlayerID,
		&i.HeightCm,
		&i.WeightKg,
		&i.GroupRole,
		&i.Position,
		&i.Age,
		&i.HeightDesc,
		&i.WeightDesc,
		&i.College,
		&i.JerseyNumber,
		&i.SalaryDesc,
		&i.Experience,
	)
	return i, err
}
