// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNFLPlayerProfile(ctx context.Context, arg CreateNFLPlayerProfileParams) (NflPlayerProfile, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	DeleteNFLPlayerProfile(ctx context.Context, playerID uuid.UUID) error
	DeletePlayer(ctx context.Context, id uuid.UUID) error
	GetNFLPlayerProfile(ctx context.Context, playerID uuid.UUID) (NflPlayerProfile, error)
	GetNFLPlayerProfileByExternalID(ctx context.Context, arg GetNFLPlayerProfileByExternalIDParams) (NflPlayerProfile, error)
	GetPlayer(ctx context.Context, id uuid.UUID) (Player, error)
	GetPlayerByExternalID(ctx context.Context, arg GetPlayerByExternalIDParams) (Player, error)
	UpdateNFLPlayerProfile(ctx context.Context, arg UpdateNFLPlayerProfileParams) (NflPlayerProfile, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
}

var _ Querier = (*Queries)(nil)
